accounts/urls.py
from django.contrib import admin
from django.urls import path

from .views import *

app_name = 'accounts'

urlpatterns = [
    path('register', RegisterView.as_view(), name='register'),
    path('login', LoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
]

communications/urls.py
from django.urls import path
from .views import *

app_name = "communications"

urlpatterns = [
    path('', all_messages, name="all-messages"),
    path('<slug:friend>', messages_with_one_friend, name="messages-with-one-friend"),
]

core/urls.py
from django.urls import path
from .views import *

app_name = "core"

urlpatterns = [
    path('', home, name="home"),
]

friends/urls.py
from django.urls import path
from .views import *

app_name = "friends"

urlpatterns = [
    path('find-friends', FindFriendsListView.as_view(), name="find-friends"),
    path('friend-requests', FriendRequestsListView.as_view(), name="friend-requests"),
    path('send-request/<slug:username>', send_request, name="send-request"),
    path('accept-request/<slug:friend>', accept_request, name="accept-request"),
    path('cancel-request/<slug:friend>', cancel_request, name="cancel-request"),
]

socialnetwork/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('notifications.urls')),
    path('', include('core.urls')),
    path('', include('newsfeed.urls')),
    path('', include('friends.urls')),
    path('timeline/', include('userprofile.urls')),
    path('messages/', include('communications.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/scripts.html
{% load static %}

<!-- JS Scripts -->
<script src="{% static "js/jQuery/jquery-3.4.1.js" %}"></script>
<script src="{% static "js/libs/jquery.appear.js" %}"></script>
<script src="{% static "js/libs/jquery.mousewheel.js" %}"></script>
<script src="{% static "js/libs/perfect-scrollbar.js" %}"></script>
<script src="{% static "js/libs/jquery.matchHeight.js" %}"></script>
<script src="{% static "js/libs/svgxuse.js" %}"></script>
<script src="{% static "js/libs/imagesloaded.pkgd.js" %}"></script>
<script src="{% static "js/libs/Headroom.js" %}"></script>
<script src="{% static "js/libs/velocity.js" %}"></script>
<script src="{% static "js/libs/ScrollMagic.js" %}"></script>
<script src="{% static "js/libs/jquery.waypoints.js" %}"></script>
<script src="{% static "js/libs/jquery.countTo.js" %}"></script>
<script src="{% static "js/libs/popper.min.js" %}"></script>
{#<script src="{% static "js/libs/material.min.js" %}"></script>#}
<script src="{% static "js/libs/bootstrap-select.js" %}"></script>
<script src="{% static "js/libs/smooth-scroll.js" %}"></script>
<script src="{% static "js/libs/selectize.js" %}"></script>
<script src="{% static "js/libs/swiper.jquery.js" %}"></script>
<script src="{% static "js/libs/moment.js" %}"></script>
<script src="{% static "js/libs/daterangepicker.js" %}"></script>
{#<script src="{% static "js/libs/fullcalendar.js" %}"></script>#}
{#<script src="{% static "js/libs/isotope.pkgd.js" %}"></script>#}
<script src="{% static "js/libs/ajax-pagination.js" %}"></script>
{#<script src="{% static "js/libs/Chart.js" %}"></script>#}
{#<script src="{% static "js/libs/chartjs-plugin-deferred.js" %}"></script>#}
{#<script src="{% static "js/libs/circle-progress.js" %}"></script>#}
<script src="{% static "js/libs/loader.js" %}"></script>
<script src="{% static "js/libs/run-chart.js" %}"></script>
<script src="{% static "js/libs/jquery.magnific-popup.js" %}"></script>
<script src="{% static "js/libs/jquery.gifplayer.js" %}"></script>
<script src="{% static "js/libs/mediaelement-and-player.js" %}"></script>
<script src="{% static "js/libs/mediaelement-playlist-plugin.min.js" %}"></script>
<script src="{% static "js/libs/ion.rangeSlider.js" %}"></script>
<script src="{% static "js/libs/leaflet.js" %}"></script>
<script src="{% static "js/libs/MarkerClusterGroup.js" %}"></script>

<script src="{% static "js/main.js" %}"></script>
<script src="{% static "js/libs-init/libs-init.js" %}"></script>
<script defer src="{% static "fonts/fontawesome-all.js" %}"></script>

<script src="{% static "bootstrap-5.0.2-dist/js/bootstrap.bundle.min.js" %}"></script>

<!-- SVG icons loader -->
<script src="{% static "js/svg-loader.js" %}"></script>
<!-- /SVG icons loader -->

{#<script src="https://vjs.zencdn.net/7.1.0/video.min.js"></script>#}

<script src="{% static "js/toastr.min.js" %}"></script>
<script src="{% static "js/reconnecting-websocket.js" %}"></script>
<script src="{% static "js/custom.js" %}"></script>
<script src="{% static "js/like.js" %}"></script>
<script src="{% static "js/notifications.js" %}"></script>

templates/includes/sidebar.html
<div class="col-lg-3">
    <aside class="sidebar static">
        <div class="widget">
            <h4 class="widget-title">Shortcuts</h4>
            <ul class="naves">
                <li>
                    <i class="ti-clipboard"></i>
                    <a href="{% url 'core:home' %}" title="">News feed</a>
                </li>
                <li>
                    <i class="ti-mouse-alt"></i>
                    <a href="{% url 'communications:all-messages' %}" title="">Inbox</a>
                </li>
                <li>
                    <i class="ti-user"></i>
                    <a href="{% url 'friends:find-friends' %}" title="">Find Friends</a>
                </li>
                <li>
                    <i class="ti-user"></i>
                    <a href="timeline-friends.html" title="">Friends</a>
                </li>
                <li>
                    <i class="ti-bell"></i>
                    <a href="notifications.html" title="">Notifications</a>
                </li>
                <li>
                    <i class="ti-power-off"></i>
                    <a href="{% url 'accounts:logout' %}" title="">Logout</a>
                </li>
            </ul>
        </div><!-- Shortcuts -->
    </aside>
</div><!-- sidebar -->

templates/includes/stylesheets.html
{% load static %}

<!-- Main Font -->
<script src="{% static 'js/libs/webfontloader.min.js' %}"></script>
<script>
    WebFont.load({
        google: {
            families: ['Roboto:300,400,500,700:latin']
        }
    });
</script>

<!-- Bootstrap CSS -->

<link rel="stylesheet" type="text/css" href="{% static 'bootstrap-5.0.2-dist/css/bootstrap-reboot.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap-5.0.2-dist/css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap-5.0.2-dist/css/bootstrap-grid.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/toastr.min.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"/>

<!-- Main Styles CSS -->
<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/fonts.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/chat.css' %}">

{#<link href="https://vjs.zencdn.net/7.1.0/video-js.css" rel="stylesheet"/>#}
{#<link href="https://unpkg.com/@videojs/themes@1/dist/city/index.css" rel="stylesheet">#}
{##}
{#<!-- If you'd like to support IE8 (for Video.js versions prior to v7) -->#}
{#<script src="https://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>#}